'use strict';

const QRCode = require('qrcode');

module.exports = {
    name: 'qr',
    category: 'utility',
    aliases: ['qrcode', 'makeqr'],
    description: 'Generate a QR code from any text or content',
    usage: '.qr <text>',
    ownerOnly: false,
    cooldown: 5,

    async execute(ctx) {

        const reply = async (text) => {
            await ctx.sock.sendMessage(
                ctx.from,
                {
                    text: String(text)
                },
                {
                    quoted: ctx.msg
                }
            );
        };

        try {
            // Get everything after .qr
            const content = String(
                ctx.args?.join(' ') || ''
            ).trim();

            // Check content
            if (!content) {
                return reply(
                    `❌ *Missing Content*\n\n` +
                    `Use:\n` +
                    `${ctx.prefix || '.'}qr <anything>\n\n` +
                    `Examples:\n` +
                    `• ${ctx.prefix || '.'}qr Dvary Bot\n` +
                    `• ${ctx.prefix || '.'}qr Hello World\n` +
                    `• ${ctx.prefix || '.'}qr https://github.com\n` +
                    `• ${ctx.prefix || '.'}qr 255712345678`
                );
            }

            // Generate QR
            const qrBuffer = await QRCode.toBuffer(
                content,
                {
                    type: 'png',
                    width: 1000,
                    margin: 2,
                    errorCorrectionLevel: 'H'
                }
            );

            // Send QR image
            await ctx.sock.sendMessage(
                ctx.from,
                {
                    image: qrBuffer,
                    caption:
                        `🔳 *DVARY QR CODE*\n\n` +
                        `📄 *Content:*\n` +
                        `${content}\n\n` +
                        `🤖 *Generated by Dvary Bot*`
                },
                {
                    quoted: ctx.msg
                }
            );

        } catch (error) {

            console.error('[QR ERROR]', error);

            return reply(
                `❌ *QR Generation Failed*\n\n` +
                `${error?.message || error}`
            );
        }
    }
};
